#version: '3.8'

services:
  twonumbersproducer:
    build:
      context: /
      dockerfile: /Dockerfile-TwoNumbersProducer
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafkadifferentgroup:9093
    depends_on:
      - zookeeper
      - kafka

  subtractiontwonumbersconsumer:
    build:
      context: /
      dockerfile: /Dockerfile-SubtractionTwoNumbersConsumer
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafkadifferentgroup:9093
    depends_on:
      - zookeeper
      - kafka
      - twonumbersproducer

  multiplicationtwonumbersconsumer:
    build:
      context: /
      dockerfile: /Dockerfile-MultiplicationTwoNumbersConsumer
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafkadifferentgroup:9093
    depends_on:
      - zookeeper
      - kafka
      - twonumbersproducer
       
  additiontwonumbersconsumer:
    build:
      context: /
      dockerfile: /Dockerfile-AdditionTwoNumbersConsumer
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafkadifferentgroup:9093
    depends_on:
      - zookeeper
      - kafka
      - twonumbersproducer

  divisiontwonumbersconsumer:
    build:
      context: /
      dockerfile: /Dockerfile-DivisionTwoNumbersConsumer
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafkadifferentgroup:9093
    depends_on:
      - zookeeper
      - kafka
      - twonumbersproducer

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeperdifferentgroup
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2183:2181" # Porta alternativa para Zookeeper
    networks:
      - default

  kafka:
    image: bitnami/kafka:latest
    container_name: kafkadifferentgroup
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:29093
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:29093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE # Define INSIDE para comunicacao interna entre brokers
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - "29093:29093" # Porta alternativa para Kafka
      - "9093:9093"   # Porta interna (usada por outros containeres)
    networks:
      - default

networks:
  default:
    name: kafka_different_network
    driver: bridge